"""
replay_buffer.py
-----------------
Stores (state, policy_target, value_target) triples generated by
self-play, with disk persistence so training can resume across runs
without re-generating games.

state:  encoded board, np.ndarray (19, 8, 8) float32
policy: full 4672-length target distribution (visit-count proportions,
        zero everywhere except legal moves at that position)
value:  scalar in [-1, 1], the eventual game outcome from the
        perspective of the player to move at that state
"""

from __future__ import annotations
import os
import random
from collections import deque
from dataclasses import dataclass, field

import numpy as np


@dataclass
class TrainingExample:
    state: np.ndarray    # (19, 8, 8)
    policy: np.ndarray   # (4672,)
    value: float


class ReplayBuffer:
    def __init__(self, max_size: int = 200_000):
        self.buffer: deque[TrainingExample] = deque(maxlen=max_size)

    def add_game(self, examples: list[TrainingExample]) -> None:
        self.buffer.extend(examples)

    def sample(self, batch_size: int) -> list[TrainingExample]:
        batch_size = min(batch_size, len(self.buffer))
        return random.sample(self.buffer, batch_size)

    def __len__(self) -> int:
        return len(self.buffer)

    def save(self, path: str) -> None:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        states = np.stack([e.state for e in self.buffer])
        policies = np.stack([e.policy for e in self.buffer])
        values = np.array([e.value for e in self.buffer], dtype=np.float32)
        np.savez_compressed(path, states=states, policies=policies, values=values)

    def load(self, path: str) -> None:
        data = np.load(path)
        states, policies, values = data["states"], data["policies"], data["values"]
        for s, p, v in zip(states, policies, values):
            self.buffer.append(TrainingExample(state=s, policy=p, value=float(v)))
